export const cards = [
    // {
    //   id: 1,
    //   title: "AI Artists",
    //   desc: "Add talent to AI",
    //   img: "https://images.pexels.com/photos/7532110/pexels-photo-7532110.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    // },
    // {
    //   id: 2,
    //   title: "Logo Design",
    //   desc: "Build yor brand",
    //   img: "https://images.pexels.com/photos/11295165/pexels-photo-11295165.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    // },
    {
      id: 3,
      title: "Pregnant Woman",
      desc: "friendly to",
      img: "./image/pregnant_carousel1.png",
    },
    {
      id: 4,
      title: "Senoir Citizens",
      desc: "friendly to",
      img: "./image/senior_carousel.png",
    },
    {
      id: 5,
      title: "People with Disabilities",
      desc: "friendly to",
      img: "https://d3srkhfokg8sj0.cloudfront.net/wp-content/uploads/sites/669/0123_STD_AskTrainer_Feature-696x313.png",
    },
    {
      id: 6,
      title: "Kids",
      desc: "friendly to",
      img: "https://hips.hearstapps.com/hmg-prod/images/children-exercising-in-fitness-class-royalty-free-image-135205468-1562617646.jpg",
    },
    {
      id: 7,
      title: "Youth",
      desc: "friendly to",
      img: "https://img.freepik.com/free-photo/group-people-exercising-together-outdoors_23-2151061441.jpg?size=626&ext=jpg&ga=GA1.1.1700460183.1709424000&semt=ais",
    },
    {
      id: 8,
      title: "Adults",
      desc: "friendly to",
      img: "https://www.optum.com/en/health-articles/sites/default/files/styles/article_feature/public/images/7ExercisesOlderAdultsCanDoToGetMoving-Web-1200x800-72_4.jpg?itok=DNo-22OK",
    },
  ];
  
  export const projects = [
    // {
    //   id: 1,
    //   img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
    //   pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    //   cat: "Web and Mobile Design",
    //   username: "Anna Bell",
    // },
    // {
    //   id: 2,
    //   img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
    //   pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    //   cat: "Logo Design",
    //   username: "Morton Green",
    // },
    {
      id: 3,
      img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Animated GIFs",
      username: "Emmett Potter",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Packaging Design",
      username: "Freddie Johnston",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Social Media Design",
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Illustration",
      username: "Dalton Hudson",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Book Design",
      username: "Hannah Dougherty",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Digital Marketing",
      username: "Ward Brewer",
    },
  ];
  
  export const gigs = [
    {
      id: 1,
      img: "https://www.familyeducation.com/sites/default/files/inline-images/lunges.jpg",
    //   pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Lower body exercise for strength and balance, lunging forward with each step. ",
      price: 59,
      star: 5,
      username: "Walking Lunges",
    },
    {
      id: 2,
      img: "https://gethealthyu.com/wp-content/uploads/2016/05/inclined-pushup.jpg",
      //pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Modified pushups against a wall, strengthening chest and arms with less strain.",
      price: 79,
      star: 5,
      username: "Wall Pushups",
    },
    {
      id: 3,
      img: "https://fabufit.co.za/wp-content/uploads/2017/03/Sumo-Squat-resized.jpg",
      //pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Wide-legged squats targeting inner thighs and glutes.",
      price: 112,
      star: 5,
      username: "Sumo Squats",
    },
    {
      id: 4,
      img: "https://todaysparent.mblycdn.com/tp/resized/2017/12/1600x1200/prenatal-yoga-butterfly-pose.jpg",
      //pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Sitting stretch for inner thighs and hips, improving flexibility.",
      price: 99,
      star: 4,
      username: "Butterfly Stretch",
    },
    {
      id: 5,
      img: "https://www.verywellfit.com/thmb/r5QNCxZUmjxXV6ScztoJs7ALfVo=/400x250/filters:no_upscale():max_bytes(150000):strip_icc()/Web_1500-About-A28-MountainClimb-397-81b8f16c94914aa3a52ee3f471dd9c03.jpeg",
      //pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Dynamic core exercise, mimicking climbing motion to boost heart rate.",
      price: 59,
      star: 5,
      username: "Mountain Climber",
    },
    {
      id: 6,
      img: "https://i.pinimg.com/564x/e4/e0/ee/e4e0eeac46c11addffdd78c4171cf605.jpg",
      //pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Wrist mobility exercise, rotating wrists to increase flexibility.",
      price: 79,
      star: 4,
      username: "Wrist Rotations",
    },
    {
      id: 7,
      img: "https://realhousemoms.com/wp-content/uploads/2014/11/bicep-curl-400x400.jpg",
      //pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Arm exercise using weights, targeting biceps for strength.",
      price: 89,
      star: 5,
      username: "Bicep Curl",
    },
    {
      id: 8,
      img: "https://www.verywellhealth.com/thmb/JjFbMQWYJnmYzLRCB_HaopJJ9TA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Depositphotos_11558348_original-56a05fe93df78cafdaa14dcc.jpg",
      //pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Seated or lying stretch for spine and back muscles, aiding flexibility and relaxation.",
      price: 110,
      star: 4,
      username: "Spinal Twist",
    },
  ];